### ISSUE TITLE
MinFS driver endpoint parameter should leverage Swarm service discovery

### ISSUE THREAD

**Issue by holgerstolzenberg** [minio/minfs#48]
Imagine the following situation: You have Docker Swarm cluster up and running.

Then you deploy a Minio service to it so that you get your storage backend running from within the swarm, please see the following compose file (secrets and overlay network `ci-traefik_public` have been created previously, not shown here):

`docker stack deploy ci-minio -c minio.yml`

```yaml
version: '3.3'

networks:
  ci-traefik_public:
    external: true
    driver_opts:
      encrypted: "true"

volumes:
  minio-data:
    driver: local
  minio-config:
    driver: local

secrets:
  secret_key:
    external: true
  access_key:
    external: true

services:
  minio:
    image: minio/minio:lastest
    command: server /ci-lab
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256m
      restart_policy:
        condition: on-failure
        delay: 3s
      placement:
        constraints:
          - node.hostname == server-1
      labels:
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.protocol=http"
        - "traefik.frontend.rule=PathPrefix:/minio"
        - "traefik.docker.network=ci-traefik_public"
    ports:
      - 9001:9000
    networks:
      ci-traefik_public:
    volumes:
      - minio-data:/ci-lab
      - minio-config:/root/.minio
    secrets:
      - access_key
      - secret_key
```

Now I want to deploy another service that uses our fresh Minio service as backend. I am taking [Portainer](https://portainer.io) as example. Please see the following compose file, deployed with command:

`docker stack deploy ci-portainer -c portainer.yml`

```yaml
version: '3.3'

networks:
  ci-traefik_public:
    external: true
    driver_opts:
      encrypted: "true"

volumes:
  portainer-data:
    driver: "minio/minfs"
    driver_opts:
      endpoint: http://192.168.99.100:9001
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}
      bucket: portainer-data

services:
  portainer:
    image: portainer/portainer:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256m
      restart_policy:
        condition: on-failure
        delay: 3s
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=portainer"
        - "traefik.port=9000"
        - "traefik.protocol=http"
        - "traefik.frontend.rule=Path:/portainer"
        - "traefik.docker.network=ci-traefik_public"
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    networks:
      - ci-traefik_public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
```

Here, using some swarm node IP and the exposed port `9001` for Minio `endpoint` parameter, everything works like a charm.

Changing the `endpoint` param to a service name breaks the deployment as the volume doesn´t get created, I tried:

* `endpoint: http://minio:9000`
* `endpoint: http://ci-minio_minio:9000`

Having to know the IP of service makes deployment more complex than needed. Sure, one might setup some DNS and it will work, but having both services within the same Swarm, this makes no sense.
